spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentDB?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      dialect: com.pivotal.gemfirexd.hibernate.GemFireXDDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create

