spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentDB?createDatabaseIfNotExist=true
    username: root
    password: passme
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#      dialect: org.hibernate.dialect.MySQL5Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
  application:
    name: student-service